//
// Created by marcin on 09.04.16.
//

#include "SyntaxListModel.h"

QList<SyntaxModel> SyntaxListModel::getSyntaxList() {
    QList<SyntaxModel> list = QList<SyntaxModel>();

    list.append(SyntaxModel("", "auto detect"));
    list.append(SyntaxModel("abap", "ABAP"));
    list.append(SyntaxModel("actionscript", "ActionScript"));
    list.append(SyntaxModel("ada", "Ada"));
    list.append(SyntaxModel("apache", "Apache configuration"));
    list.append(SyntaxModel("applescript", "AppleScript"));
    list.append(SyntaxModel("apt_sources", "Apt sources"));
    list.append(SyntaxModel("asm", "ASM"));
    list.append(SyntaxModel("asp", "ASP"));
    list.append(SyntaxModel("autoconf", "Autoconf"));
    list.append(SyntaxModel("autohotkey", "Autohotkey"));
    list.append(SyntaxModel("autoit", "AutoIt"));
    list.append(SyntaxModel("avisynth", "AviSynth"));
    list.append(SyntaxModel("awk", "awk"));
    list.append(SyntaxModel("bash", "Bash"));
    list.append(SyntaxModel("basic4gl", "Basic4GL"));
    list.append(SyntaxModel("bibtex", "BibTeX"));
    list.append(SyntaxModel("blitzbasic", "BlitzBasic"));
    list.append(SyntaxModel("bnf", "bnf"));
    list.append(SyntaxModel("boo", "Boo"));
    list.append(SyntaxModel("bf", "Brainfuck"));
    list.append(SyntaxModel("c", "C"));
    list.append(SyntaxModel("csharp", "C#"));
    list.append(SyntaxModel("c_mac", "C (Mac)"));
    list.append(SyntaxModel("cpp", "C++"));
    list.append(SyntaxModel("cpp-qt", "C++ (QT)"));
    list.append(SyntaxModel("caddcl", "CAD DCL"));
    list.append(SyntaxModel("cadlisp", "CAD Lisp"));
    list.append(SyntaxModel("cfdg", "CFDG"));
    list.append(SyntaxModel("chaiscript", "ChaiScript"));
    list.append(SyntaxModel("cil", "CIL"));
    list.append(SyntaxModel("clojure", "Clojure"));
    list.append(SyntaxModel("cmake", "CMake"));
    list.append(SyntaxModel("cobol", "COBOL"));
    list.append(SyntaxModel("cfm", "ColdFusion"));
    list.append(SyntaxModel("css", "CSS"));
    list.append(SyntaxModel("cuesheet", "Cuesheet"));
    list.append(SyntaxModel("d", "D"));
    list.append(SyntaxModel("dcs", "DCS"));
    list.append(SyntaxModel("delphi", "Delphi"));
    list.append(SyntaxModel("diff", "Diff"));
    list.append(SyntaxModel("div", "DIV"));
    list.append(SyntaxModel("dos", "DOS"));
    list.append(SyntaxModel("dot", "dot"));
    list.append(SyntaxModel("ecmascript", "ECMAScript"));
    list.append(SyntaxModel("eiffel", "Eiffel"));
    list.append(SyntaxModel("email", "eMail (mbox)"));
    list.append(SyntaxModel("erlang", "Erlang"));
    list.append(SyntaxModel("fsharp", "F#"));
    list.append(SyntaxModel("fo", "FO (abas-ERP)"));
    list.append(SyntaxModel("fortran", "Fortran"));
    list.append(SyntaxModel("freebasic", "FreeBasic"));
    list.append(SyntaxModel("4cs", "GADV 4CS"));
    list.append(SyntaxModel("gambas", "GAMBAS"));
    list.append(SyntaxModel("gdb", "GDB"));
    list.append(SyntaxModel("genero", "genero"));
    list.append(SyntaxModel("genie", "Genie"));
    list.append(SyntaxModel("glsl", "glSlang"));
    list.append(SyntaxModel("gml", "GML"));
    list.append(SyntaxModel("gettext", "GNU Gettext"));
    list.append(SyntaxModel("make", "GNU make"));
    list.append(SyntaxModel("gnuplot", "Gnuplot"));
    list.append(SyntaxModel("groovy", "Groovy"));
    list.append(SyntaxModel("gwbasic", "GwBasic"));
    list.append(SyntaxModel("haskell", "Haskell"));
    list.append(SyntaxModel("hicest", "HicEst"));
    list.append(SyntaxModel("hq9plus", "HQ9+"));
    list.append(SyntaxModel("html4strict", "HTML"));
    list.append(SyntaxModel("icon", "Icon"));
    list.append(SyntaxModel("ini", "INI"));
    list.append(SyntaxModel("inno", "Inno"));
    list.append(SyntaxModel("intercal", "INTERCAL"));
    list.append(SyntaxModel("io", "Io"));
    list.append(SyntaxModel("j", "J"));
    list.append(SyntaxModel("java", "Java"));
    list.append(SyntaxModel("java5", "Java(TM) 2 Platform Standard"));
    list.append(SyntaxModel("javascript", "Javascript"));
    list.append(SyntaxModel("jquery", "jQuery"));
    list.append(SyntaxModel("kixtart", "KiXtart"));
    list.append(SyntaxModel("klonec", "KLone C"));
    list.append(SyntaxModel("klonecpp", "KLone C++"));
    list.append(SyntaxModel("latex", "LaTeX"));
    list.append(SyntaxModel("lisp", "Lisp"));
    list.append(SyntaxModel("locobasic", "Locomotive Basic"));
    list.append(SyntaxModel("logtalk", "Logtalk"));
    list.append(SyntaxModel("lolcode", "LOLcode"));
    list.append(SyntaxModel("lotusformula", "Lotus Notes @Formulas"));
    list.append(SyntaxModel("lotusscript", "LotusScript"));
    list.append(SyntaxModel("lscript", "LScript"));
    list.append(SyntaxModel("lsl2", "LSL2"));
    list.append(SyntaxModel("lua", "Lua"));
    list.append(SyntaxModel("magiksf", "MagikSF"));
    list.append(SyntaxModel("mapbasic", "MapBasic"));
    list.append(SyntaxModel("matlab", "Matlab M"));
    list.append(SyntaxModel("mpasm", "Microchip Assembler"));
    list.append(SyntaxModel("reg", "Microsoft Registry"));
    list.append(SyntaxModel("mirc", "mIRC Scripting"));
    list.append(SyntaxModel("mmix", "MMIX"));
    list.append(SyntaxModel("modula2", "Modula-2"));
    list.append(SyntaxModel("modula3", "Modula-3"));
    list.append(SyntaxModel("m68k", "Motorola 68000 Assembler"));
    list.append(SyntaxModel("mxml", "MXML"));
    list.append(SyntaxModel("mysql", "MySQL"));
    list.append(SyntaxModel("newlisp", "newlisp"));
    list.append(SyntaxModel("nsis", "NSIS"));
    list.append(SyntaxModel("oberon2", "Oberon-2"));
    list.append(SyntaxModel("objc", "Objective-C"));
    list.append(SyntaxModel("ocaml", "OCaml"));
    list.append(SyntaxModel("ocaml-brief", "OCaml (brief)"));
    list.append(SyntaxModel("pf", "OpenBSD Packet Filter"));
    list.append(SyntaxModel("oobas", "OpenOffice.org Basic"));
    list.append(SyntaxModel("oracle8", "Oracle 8 SQL"));
    list.append(SyntaxModel("oracle11", "Oracle 11 SQL"));
    list.append(SyntaxModel("oxygene", "Oxygene (Delphi Prism)"));
    list.append(SyntaxModel("oz", "OZ"));
    list.append(SyntaxModel("pascal", "Pascal"));
    list.append(SyntaxModel("pcre", "PCRE"));
    list.append(SyntaxModel("per", "per"));
    list.append(SyntaxModel("perl", "Perl"));
    list.append(SyntaxModel("perl6", "Perl 6"));
    list.append(SyntaxModel("php", "PHP"));
    list.append(SyntaxModel("php-brief", "PHP (brief)"));
    list.append(SyntaxModel("pic16", "PIC16"));
    list.append(SyntaxModel("pike", "Pike"));
    list.append(SyntaxModel("pixelbender", "Pixel Bender 1.0"));
    list.append(SyntaxModel("plsql", "PL/SQL"));
    list.append(SyntaxModel("text", "Plain Text"));
    list.append(SyntaxModel("postgresql", "PostgreSQL"));
    list.append(SyntaxModel("povray", "POVRAY"));
    list.append(SyntaxModel("powerbuilder", "PowerBuilder"));
    list.append(SyntaxModel("powershell", "PowerShell"));
    list.append(SyntaxModel("progress", "Progress"));
    list.append(SyntaxModel("prolog", "Prolog"));
    list.append(SyntaxModel("properties", "PROPERTIES"));
    list.append(SyntaxModel("providex", "ProvideX"));
    list.append(SyntaxModel("purebasic", "PureBasic"));
    list.append(SyntaxModel("python", "Python"));
    list.append(SyntaxModel("q", "q/kdb+"));
    list.append(SyntaxModel("qbasic", "QBasic/QuickBASIC"));
    list.append(SyntaxModel("rsplus", "R / S+"));
    list.append(SyntaxModel("rails", "Rails"));
    list.append(SyntaxModel("rebol", "REBOL"));
    list.append(SyntaxModel("robots", "robots.txt"));
    list.append(SyntaxModel("rpmspec", "RPM Specification File"));
    list.append(SyntaxModel("ruby", "Ruby"));
    list.append(SyntaxModel("sas", "SAS"));
    list.append(SyntaxModel("scala", "Scala"));
    list.append(SyntaxModel("scheme", "Scheme"));
    list.append(SyntaxModel("scilab", "SciLab"));
    list.append(SyntaxModel("sdlbasic", "sdlBasic"));
    list.append(SyntaxModel("smalltalk", "Smalltalk"));
    list.append(SyntaxModel("smarty", "Smarty"));
    list.append(SyntaxModel("sql", "SQL"));
    list.append(SyntaxModel("systemverilo", "SystemVerilog"));
    list.append(SyntaxModel("tsql", "T-SQL"));
    list.append(SyntaxModel("tcl", "TCL"));
    list.append(SyntaxModel("teraterm", "Tera Term Macro"));
    list.append(SyntaxModel("thinbasic", "thinBasic"));
    list.append(SyntaxModel("typoscript", "TypoScript"));
    list.append(SyntaxModel("unicon", "Unicon (Unified Extended Dialect)"));
    list.append(SyntaxModel("idl", "Uno Idl"));
    list.append(SyntaxModel("vala", "Vala"));
    list.append(SyntaxModel("vbnet", "vb.net"));
    list.append(SyntaxModel("verilog", "Verilog"));
    list.append(SyntaxModel("vhdl", "VHDL"));
    list.append(SyntaxModel("vim", "Vim Script"));
    list.append(SyntaxModel("vb", "Visual Basic"));
    list.append(SyntaxModel("visualfoxpro", "Visual Fox Pro"));
    list.append(SyntaxModel("visualprolog", "Visual Prolog"));
    list.append(SyntaxModel("whitespace", "Whitespace"));
    list.append(SyntaxModel("whois", "Whois (RPSL format)"));
    list.append(SyntaxModel("winbatch", "Winbatch"));
    list.append(SyntaxModel("xpp", "X++"));
    list.append(SyntaxModel("xbasic", "XBasic"));
    list.append(SyntaxModel("xml", "XML"));
    list.append(SyntaxModel("xorg_conf", "Xorg configuration"));
    list.append(SyntaxModel("z80", "ZiLOG Z80 Assembler"));

    return list;
}

